name: Setup WP Env
description: Setup WordPress environment for testing

inputs:
    wp:
        description: WordPress version (e.g. `5.8`, `6.6`)
        required: false
    php:
        description: PHP version (e.g. `7.4`, `8.0`)
        required: false
    plugins:
        description: A comma separated list of plugins to install (e.g. `./path/to/plugin, elementor/elementor#main, https://localhost/path/to/plugin.zip`)
        required: false
        default: ''
    themes:
        description: A comma separated list of themes to install (e.g. `./path/to/theme, elementor/hello-elementor#main, https://localhost/path/to/theme.zip`)
        required: false
        default: ''
    active-theme:
        description: The slug of a theme to activate (e.g. `hello-elementor`)
        required: false
        default: ''
    mappings:
        description: Mappings directories into the WordPress container (e.g. `templates:/path/to/local/templates,plugins:/path/to/local/plugins`) (separator can be ',' or '\n')
        required: false
        default: ''
    config:
        description: Set env configuration on the WordPress container (e.g. `ELEMENTOR_SHOW_HIDDEN_EXPERIMENTS:true,SOME_STRING:"THIS IS SOME STRING"`) (separator can be ',' or '\n')
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Install wp-env
          shell: bash
          run: npm i -g @wordpress/env@10

        - name: Creating wp-env config file
          env:
              INPUT_WP: ${{ inputs.wp }}
              INPUT_PHP: ${{ inputs.php }}
              INPUT_PLUGINS: ${{ inputs.plugins }}
              INPUT_THEMES: ${{ inputs.themes }}
              INPUT_ACTIVE_THEME: ${{ inputs.active-theme }}
              INPUT_MAPPINGS: ${{ inputs.mappings }}
              ACTION_PATH: ${{ github.action_path }}
              INPUT_CONFIG: ${{ input.config }}
          run: |
              npx zx@8 $ACTION_PATH/../../../dist/setup-wp-env/create-wp-env-config.js \
              --wp="$INPUT_WP" \
              --php="$INPUT_PHP" \
              --plugins="$INPUT_PLUGINS" \
              --themes="$INPUT_THEMES" \
              --active-theme="$INPUT_ACTIVE_THEME" \
              --mappings="$INPUT_ACTIVE_THEME" \
              --config="$INPUT_CONFIG" \
              --dir="./.wp-env-tmp"
          shell: bash

        - name: Output wp-env config file
          run: cat ./.wp-env-tmp/.wp-env.json
          shell: bash

        - name: Run wp-env
          run: cd ./.wp-env-tmp && npx wp-env start
          shell: bash

        - name: Cleanup wp-env tmp directory
          run: rm -rf ./.wp-env-tmp
          shell: bash
