name: Setup WP Env
description: Setup WordPress environment for testing

inputs:
    wp:
        description: WordPress version (e.g. `5.8`, `6.6`)
        required: false
    php:
        description: PHP version (e.g. `7.4`, `8.0`)
        required: false
    plugins:
        description: A comma separated list of plugins to install (e.g. `./path/to/plugin, elementor/elementor#main, https://localhost/path/to/plugin.zip`)
        required: false
        default: ''
    themes:
        description: A comma separated list of themes to install (e.g. `./path/to/theme, elementor/hello-elementor#main, https://localhost/path/to/theme.zip`)
        required: false
        default: ''
    active-theme:
        description: The slug of a theme to activate (e.g. `hello-elementor`)
        required: false
        default: ''
    mappings:
        description: A list of directory mapping between your machine and the WordPress container, separated by commas or new lines (e.g. `templates:/path/to/local/templates, plugins:/path/to/local/plugins`)
        required: false
        default: ''
    config:
        description: A list of PHP constants that'll be passed to the WordPress container, separated by commas or new lines (e.g. `WP_MEMORY_LIMIT:64M, WPLANG:en_US`)
        required: false
        default: ''
    wp-debug:
        description: Enable WordPress debug mode (turn on WP_DEBUG and SCRIPT_DEBUG)
        required: false
        default: 'false'

runs:
    using: composite
    steps:
        - name: Install wp-env
          shell: bash
          run: npm i -g @wordpress/env@10

        - name: Creating wp-env config file
          env:
              INPUT_WP: ${{ inputs.wp }}
              INPUT_PHP: ${{ inputs.php }}
              INPUT_PLUGINS: ${{ inputs.plugins }}
              INPUT_THEMES: ${{ inputs.themes }}
              INPUT_ACTIVE_THEME: ${{ inputs.active-theme }}
              INPUT_MAPPINGS: ${{ inputs.mappings }}
              ACTION_PATH: ${{ github.action_path }}
              INPUT_CONFIG: ${{ inputs.config }}
          run: |
              npx zx@8 $ACTION_PATH/dist/create-wp-env-config.js \
              --wp="$INPUT_WP" \
              --php="$INPUT_PHP" \
              --plugins="$INPUT_PLUGINS" \
              --themes="$INPUT_THEMES" \
              --active-theme="$INPUT_ACTIVE_THEME" \
              --mappings="$INPUT_MAPPINGS" \
              --config="$INPUT_CONFIG" \
          shell: bash

        - name: Run wp-env
          run: npx wp-env start
          shell: bash
