name: Test Actions

on: [pull_request, workflow_dispatch]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-wp-env:
        name: Setup WP Env
        runs-on: ubuntu-latest
        if: startsWith( github.repository, 'elementor/' )
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup WP Env
              uses: ./.github/actions/setup-wp-env
              with:
                  php: '8.0'
                  wp: '6.6'
                  themes: 'https://downloads.wordpress.org/theme/hello-elementor.zip'
                  active-theme: 'hello-elementor'
                  config: |-
                      ELEMENTOR_SHOW_HIDDEN_EXPERIMENTS:1
                      WP_DEBUG:0
