name: Test Actions

on: [pull_request, workflow_dispatch]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-wp-env:
        name: Setup WP and Elementor env
        runs-on: ubuntu-latest
        if: startsWith( github.repository, 'elementor/' )
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup WP Env
              uses: ./actions/setup-wp-env
              with:
                  php: '8.0'
                  wp: '6.6'
                  active-theme: 'hello-elementor'
                  themes: |-
                      https://downloads.wordpress.org/theme/hello-elementor.zip
                  plugins: |-
                      https://downloads.wordpress.org/plugin/elementor.zip
                  mappings: |-
                      elementor-templates:./tests/elementor-templates
                  config: |-
                      ELEMENTOR_SHOW_HIDDEN_EXPERIMENTS:1

            - name: Setup Elementor Env
              uses: ./actions/setup-elementor-env
              with:
                  env: 'development'
                  experiments: |-
                      atomic_widgets:true
                      e_onboarding:false
                  templates: |-
                      elementor-templates

            - name: Test setup env
              run: |
                  ls  -la ./.wp-env-tmp
